### ISSUE TITLE
Loading bar on business registration

### ISSUE THREAD

**Issue by Medo3G** [SEGUC17/mean_squad#228]
**1. Severity:** 
Low
**2. Reported by:** 
Mohamed Mohy
**3. Description:**
A loading bar appears after finishing registration, and doesn't fill up or do anything.
**4. Steps to reproduce the issue:**
1) Register as a business using valid info.
2) Press "register"
3) Sign up successful page appears. However, a loading bar starts and never finishes.

**5. Expected result:**
Either that loading bar finishes and does something, or it doesn't appear in the first place. 

![image](https://cloud.githubusercontent.com/assets/12884373/25580639/c0dbc9be-2e82-11e7-8ba6-91dd724d2ca8.png)

**Comment by IElgohary** [comment]
#223 duplicate

**Comment by melzareix** [comment]
Please close it
