### ISSUE TITLE
Loading bar does not disappear after a successful sign up

### ISSUE THREAD

**Issue by abdo-shabrawy** [SEGUC17/mean_squad#230]
1. Severity:
Low

2. Reported by:
Abdelrahman A. Elshabrawy

3. Description:
The loading bar does not disappear after a successful sign up, even though the "welcome" page appears and the "Thank You For registering" message appears.

4. Steps to reproduce the issue:
Sign up with valid information.

5. Expected result:
The loading bar should disappear after loading the page.

**Comment by ameniawy** [comment]
3rd duplicate

**Comment by IElgohary** [comment]
#223

**Comment by melzareix** [comment]
Please close it
