### ISSUE TITLE
Client Age validation

### ISSUE THREAD

**Issue by abdo-shabrawy** [SEGUC17/mean_squad#231]
1. Severity:
Low

2. Reported by:
Abdelrahman A. Elshabrawy

3. Description:
A client can create an account with a birthdate of 01/01/0001 A.D.

4. Steps to reproduce the issue:
Sign up and select an extremely old birthdate.

5. Expected result:
The user should not be allowed to sign up with "Bogus" data. A cap of 125 years of age (for example)  should be placed.

**Comment by IElgohary** [comment]
Duplicate and this will not affect the backend

**Comment by IElgohary** [comment]
#212
