### ISSUE TITLE
Details field in reservation disappears after filling in enough fields

### ISSUE THREAD

**Issue by abdo-shabrawy** [SEGUC17/mean_squad#238]
1. Severity:
Low

2. Reported by:
Abdelrahman A. Elshabrawy

3. Description:
When reserving an activity, after filling out each field, the form contents scroll up but the scroll bar does not change. If all the fields are filled out (excluding the details field) and you click reserve,  you are prompted to fill the Details field, which is impossible until you remove the info you supplied in the previously filled participants field.

4. Steps to reproduce the issue:
Login as a client.
Visit the reservation page of a business.
Fill in the fields, ignoring the details field.
Click reserve.

5. Expected result:
The Details field should be accessible throughout the reservation process, without the need to remove any information.

6. Screenshots:
![details](https://cloud.githubusercontent.com/assets/20780298/25582952/06f9de7e-2e90-11e7-90e8-671a57fc26b7.png)

**Comment by ameniawy** [comment]
can't reproduce your problem, you are probably zoomed in from your browser as I noticed the navbar is too big.
proof:
![image](https://cloud.githubusercontent.com/assets/17433149/25583175/f33e040e-2e90-11e7-9354-e43317be35de.png)

**Comment by abdo-shabrawy** [comment]
It has nothing to do with zoom (it was set to the default 100%), it does however have something to do with form resizing/scroll option when a window is not maximized or on smaller screen resolution.

**Comment by IElgohary** [comment]
Duplicate #220
