### ISSUE TITLE
Price doesn't change when using a promotion

### ISSUE THREAD

**Issue by yousseffarahat** [SEGUC17/mean_squad#241]
1. **Severity:** 
Medium
2. **Reported by:** 
 Youssef Farahat
3. **Description:**
 When reserving an activity the price value doesn't change when using a promotion
4. **Steps to reproduce the issue:**
1)Login to the system as a client
2) Reserve an activity with a promotion
![image](https://cloud.githubusercontent.com/assets/25284441/25583526/76894d0e-2e92-11e7-9436-523738660f5e.png)
![image](https://cloud.githubusercontent.com/assets/25284441/25583532/7dc0f90a-2e92-11e7-9bea-3296c25111e9.png)
![image](https://cloud.githubusercontent.com/assets/25284441/25583654/1377b93e-2e93-11e7-9b22-3556eb33dab9.png)

5. **Expected result:**
40% discount, Actual no change on reservation form or when paying

**Comment by ameniawy** [comment]
It does change if you wait a few seconds until it's applied

**Comment by yousseffarahat** [comment]
I used 40% reserved and had to pay the full amount
as seen in this screenshot
![image](https://cloud.githubusercontent.com/assets/25284441/25583785/a8402f4c-2e93-11e7-9b78-7550d79e1f1c.png)

**Comment by yousseffarahat** [comment]
Also, i waited 5 minutes still no change
![image](https://cloud.githubusercontent.com/assets/25284441/25583826/d3fee65a-2e93-11e7-84db-f686a6f76bc7.png)
![image](https://cloud.githubusercontent.com/assets/25284441/25584010/954d243e-2e94-11e7-9bdf-47795a156102.png)

**Comment by ameniawy** [comment]
Without a promotion
![image](https://cloud.githubusercontent.com/assets/17433149/25583854/ea4264a0-2e93-11e7-8e80-47cf36fa8907.png)

With a promotion

**Comment by ameniawy** [comment]
Closed it by mistake

**Comment by melzareix** [comment]
@ameniawy You can reopen it

**Comment by yousseffarahat** [comment]
Added a new issue, if u reopen it, close the other

**Comment by abdo-shabrawy** [comment]
By the way, It is not the same activity or number of participants.
Football Gathering (Chelsea vs Spurs), 8 
and Football Escape room, 4
