### ISSUE TITLE
Editing activity edits listing info

### ISSUE THREAD

**Issue by Medo3G** [SEGUC17/mean_squad#252]
**1. Severity:** 
Low

**2. Reported by:** 
Mohamed Mohy

**3. Description:** 
If a business edits its activity, the data in the text boxes is linked to the values of the listing in the page. Even if the edit dialog box is closed without actually editing.

**4. Steps to reproduce the issue:** 

1. Sign in as a business

2. Edit activity image, name or description text

3. Do not actually edit.

**5. Expected result:**
The activity info should not be changed, however the info fields contain the new values, (in the case of the image, a broken image) instead of the correct info in the listing grid. 

Note: The fields are not edited in the backend, it's just that they change on the page when they shouldn't. Once again, a refresh fixes this.

**Comment by IElgohary** [comment]
I believe this is a duplicate to #248
