### ISSUE TITLE
SignUp Form

### ISSUE THREAD

**Issue by TheRealImaginary** [SEGUC17/mean_squad#255]
**1. Severity:** Low

**2. Reported by:** Mazen Magdy

**3. Description:** Neither the `Client` nor `Business` tabs are colored when page is loaded. Moreover the `Contact Us` link is not aligned properly

**4. Steps to reproduce the issue:** Click Signup

**5. Expected result:** A Default one should be colored giving feedback to the user.
![issue1](https://cloud.githubusercontent.com/assets/24315020/25589369/a11da1fe-2eac-11e7-89a9-0d82a3e4212a.png)

**Comment by melzareix** [comment]
I think this might be a duplicate of #211.

**Comment by IElgohary** [comment]
both bugs have been addressed in other issues
